xpilot-4.4.2

diff --git a/src/common/NT/bindist/makeDistribution b/src/common/NT/bindist/makeDistribution
--- a/src/common/NT/bindist/makeDistribution
+++ b/src/common/NT/bindist/makeDistribution
@@ -1,5 +1,5 @@
 #!/bin/bash
-# $Id: makeDistribution,v 5.4 2001/06/26 09:55:16 dik Exp $
+# $Id: makeDistribution,v 5.6 2001/09/24 17:41:17 dik Exp $
 # makeDistribution - a script to move things to a directory to make the build script
 #                    and then call makensis to build a Windows binary distribution for
 #                    XPilot, a multiplayer gravity war game.  
@@ -26,6 +26,7 @@ XDIR=//e/XPilot
 XPWHODIR="xpwho"	# sibling of our parent's dirname
 #MAPXPRESSDIR="staged/mapxpress"
 MAPXPRESSDIR="mapxpress"
+XPREPLAYDIR="replay"
 XPSHIPEDITORDIR="staged/XPShipEditor"
 
 ECHO_ON="set -x"
@@ -191,6 +192,24 @@ then
 	fi
 fi
 
+# go make XPreplay.exe 
+if [ $QUICK = N ]
+then
+	echo go make XPreplay.exe 
+	cd $BASE/src/replay/NT
+	if [ $ALL = Y ]
+	then
+		echo "CLEAN `pwd`"
+		nmake CLEAN /NOLOGO /f XPreplay.mak CFG="XPreplay - Win32 Release"
+	fi
+	nmake /f XPreplay.mak CFG="XPreplay - Win32 Release"
+	if [ $? != 0 ]
+	then
+		echo "makeDistribution: failed to build XPreplay.exe"
+		exit 1
+	fi
+fi
+
 # and go make mapxpress.chm
 if [ $QUICK = N -a $BUILDHELP = Y ]
 then
@@ -229,16 +248,20 @@ cp -p res/xpilot.ico	$XDIR
 
 cd $BASE/src/server/NT
 cp -p Release/XPilotServer.exe $XDIR
+cp -p Release/ServerOpts.txt $XDIR/doc
 
 cd $BASE/src/common/NT/bindist
 cp -p XPilot.nsi 		$XDIR		# don't install the NSI, but we use it there.
 cp -p xp_off.bmp 		$XDIR		# nsi helper bitmap
 cp -p xp_on.bmp 		$XDIR		# nsi helper bitmap
-cp -p ServerOpts.txt	$XDIR/doc	# this file is generated by hand from linux `xpilots -help`
 cp -p READMEbin.txt		$XDIR/README.txt
 
 cd $BASE/../$XPWHODIR/WinRel
 cp -p XPwho.exe 		$XDIR
+
+cd $BASE/src/replay/NT
+cp -p Release/XPreplay.exe		$XDIR
+cp -p XPreplay.reg				$XDIR
 
 cd $BASE/../$MAPXPRESSDIR
 cp -p Release/MapXpress.exe		$XDIR/MapXpress
@@ -254,11 +277,11 @@ cp -p XPShipEditor.exe	$XDIR/XPShipEditor
 cp -p XPShipEditor.txt	$XDIR/XPShipEditor
 
 cd $BASE/doc
-cp -p BUGS 				$XDIR/doc/Bugs.txt
+#cp -p BUGS 				$XDIR/doc/Bugs.txt
 cp -p ChangeLog			$XDIR/doc/ChangeLog.txt
 cp -p CREDITS			$XDIR/doc/Credits.txt
 cp -p FAQ				$XDIR/doc/FAQ.txt
-cp -p FIXED				$XDIR/doc/Fixed.txt
+#cp -p FIXED				$XDIR/doc/Fixed.txt
 cp -p README.MAPS		$XDIR/doc/README.MAPS.txt
 cp -p README.MAPS2		$XDIR/doc/README.MAPS2.txt
 cp -p README.SHIPS		$XDIR/doc/README.SHIPS.txt
